### ISSUE TITLE
Question about ImageNet-Subset ablation experiments

### ISSUE THREAD

**Issue by SeminKim** [wangkai930418/attndistill#1]
Hi, thanks for sharing the code for your work!
I have some questions about the ablation study done in the ImageNet-Subset.
1. Is the dataset chosen randomly from full ImageNet or same to one that is commonly used(e.g. [here](https://github.com/HobbitLong/CMC/blob/master/imagenet100.txt))? 
2. Do you have any plan to release the MAE teacher model checkpoint / or ablation experiment code?

Thanks.

**Comment by wangkai930418** [comment]
Hi, 

1, The ImageNet-Subset is a classical dataset used in continual learning ([iCaRL](https://github.com/srebuffi/iCaRL), [LUCIR](https://github.com/wuyuebupt/LargeScaleIncrementalLearning/tree/master/dataImageNet100)).

2, Since there are some disk usage limitations on the servers, I already removed all old projects. So sorry that I cannot share the pretrained model over ImageNet-Subset. But the main experiment over ImageNet-full are conducted over released checkpoints from other methods, you can download them from their GitHub repos.

Best,
